-- ============================================================================
-- Persian Diet App — Supabase Schema
-- Run this in the Supabase SQL Editor (or via `supabase db push`).
-- ============================================================================

-- Enable UUID generation if not already enabled
create extension if not exists "uuid-ossp";

-- ============================================================================
-- TABLE: food_exchanges
-- Reference nutrition data. Read-only for clients (public read, no write).
-- ============================================================================

create table if not exists public.food_exchanges (
  id text primary key,
  category text not null check (
    category in (
      'starch',
      'meat_lean',
      'meat_medium_fat',
      'meat_high_fat',
      'meat_very_lean',
      'vegetable',
      'fruit',
      'dairy_skim',
      'dairy_low_fat',
      'dairy_whole',
      'fat',
      'mixed_dish',
      'legume'
    )
  ),
  name text not null,
  amount text not null,
  "weightGrams" int4 not null,
  kcal int4 not null,
  carbs int4 not null,
  protein int4 not null,
  fat int4 not null,
  fiber int4 not null default 0,
  sugar int4 not null default 0,
  gi_level text not null check (gi_level in ('Low', 'Medium', 'High'))
);

comment on table public.food_exchanges is
  'Deterministic food exchange reference table. Never generated by AI.';

alter table public.food_exchanges enable row level security;

create policy "food_exchanges are publicly readable"
  on public.food_exchanges
  for select
  using (true);

-- No insert/update/delete policies for anon/authenticated roles:
-- this table is managed only via the service role (admin/CMS).

-- ============================================================================
-- TABLE: user_profiles
-- One row per authenticated user (id = auth.users.id).
-- ============================================================================

create table if not exists public.user_profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  phone text,
  gender text check (gender in ('male', 'female')),
  province text,
  city text,
  birth_date date,
  height numeric,
  weight numeric,
  goal text check (goal in ('weight_loss', 'weight_gain', 'maintenance')),
  activity_level text check (activity_level in ('sedentary', 'moderate', 'active')),
  workout_location text check (workout_location in ('home', 'gym', 'none')),
  workout_days int2,
  motivation text,
  schedule_json jsonb,
  medical_conditions_json jsonb,
  dietary_preferences_json jsonb,
  weight_loss_speed text check (weight_loss_speed in ('mild', 'standard', 'fast')),
  body_fat_pct numeric,
  body_type text check (body_type in ('ectomorph', 'mesomorph', 'endomorph')),
  subscription_tier text check (subscription_tier in ('silver', 'gold')),
  created_at timestamptz not null default now()
);

comment on table public.user_profiles is
  'Onboarding + profile data. Nutrition numbers are computed client-side via nutritionHelpers.ts, never stored as AI output.';

alter table public.user_profiles enable row level security;

create policy "Users can view their own profile"
  on public.user_profiles
  for select
  using (auth.uid() = id);

create policy "Users can insert their own profile"
  on public.user_profiles
  for insert
  with check (auth.uid() = id);

create policy "Users can update their own profile"
  on public.user_profiles
  for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- ============================================================================
-- Helpful index for lookups
-- ============================================================================

create index if not exists idx_food_exchanges_category
  on public.food_exchanges (category);

create index if not exists idx_user_profiles_phone
  on public.user_profiles (phone);
