-- Behtan tested nutrition catalog seed.
-- Generated from the local Nutrition v2 + Portion Realism + Iranian Menus catalog.

begin;
insert into public.food_items (
  id, name, role, emoji, unit_label, grams_per_unit, kcal_per_unit, protein_per_unit, carbs_per_unit, fat_per_unit,
  allergy_flags, excluded_for_vegetarian, portion_min_units, portion_typical_units, portion_soft_max_units, portion_hard_max_units, portion_step,
  is_active, sort_order
) values
  ('egg_white', 'سفیده تخم‌مرغ', 'protein', '🥚', 'عدد', 33, 17, 3.6, 0.2, 0.1, '{}'::text[], array['vegan']::text[], 1, 3, 5, 6, 1, true, 0),
  ('egg_whole', 'تخم‌مرغ کامل', 'protein', '🥚', 'عدد', 50, 78, 6.3, 0.6, 5.3, '{}'::text[], array['vegan']::text[], 1, 2, 3, 4, 1, true, 1),
  ('chicken_breast', 'سینه مرغ پخته', 'protein', '🍗', 'گرم', 100, 165, 31, 0, 3.6, '{}'::text[], array['vegan','lacto_ovo','raw']::text[], 0.5, 1.5, 2, 2.5, 0.25, true, 2),
  ('grilled_fish', 'ماهی کبابی', 'protein', '🐟', 'گرم', 100, 128, 20, 0, 5, array['seafood']::text[], array['vegan','lacto_ovo','raw']::text[], 0.5, 1.5, 2, 2.5, 0.25, true, 3),
  ('lean_beef', 'گوشت گاو کم‌چرب', 'protein', '🥩', 'گرم', 100, 175, 26, 0, 7, '{}'::text[], array['vegan','lacto_ovo','pescatarian','raw']::text[], 0.5, 1.5, 2, 2.25, 0.25, true, 4),
  ('ground_beef_lean', 'گوشت چرخ‌کرده کم‌چرب', 'protein', '🥩', 'گرم', 100, 160, 22, 0, 8, '{}'::text[], array['vegan','lacto_ovo','pescatarian','raw']::text[], 0.5, 1.5, 2, 2.25, 0.25, true, 5),
  ('whey_protein', 'پودر پروتئین وی', 'protein', '🥤', 'اسکوپ', 30, 120, 24, 3, 2, array['dairy']::text[], array['vegan','raw']::text[], 0.5, 1, 1.5, 2, 0.5, true, 6),
  ('pea_protein', 'پروتئین نخود', 'protein', '🥤', 'اسکوپ', 30, 110, 24, 2, 1.5, '{}'::text[], '{}'::text[], 0.5, 1, 1.5, 2, 0.5, true, 7),
  ('soy_chunks', 'سویا', 'protein', '🫘', 'گرم', 100, 345, 47, 30, 1, array['soy']::text[], '{}'::text[], 0.25, 0.5, 0.75, 1, 0.25, true, 8),
  ('lentils_cooked', 'عدس پخته', 'protein', '🍲', 'گرم', 100, 116, 9, 20, 0.4, '{}'::text[], '{}'::text[], 0.5, 1.5, 2, 2.5, 0.25, true, 9),
  ('brown_rice_cooked', 'برنج قهوه‌ای پخته', 'starch', '🍚', 'گرم', 100, 112, 2.6, 23, 0.9, '{}'::text[], '{}'::text[], 0.5, 1.5, 2.25, 3, 0.25, true, 10),
  ('white_rice_cooked', 'برنج سفید پخته', 'starch', '🍚', 'گرم', 100, 130, 2.4, 28, 0.2, '{}'::text[], '{}'::text[], 0.5, 1.5, 2.25, 3, 0.25, true, 11),
  ('quinoa_cooked', 'کینوا پخته', 'starch', '🍚', 'گرم', 100, 120, 4.4, 21, 1.9, '{}'::text[], '{}'::text[], 0.5, 1.5, 2.25, 3, 0.25, true, 12),
  ('oats_dry', 'جو پرک', 'starch', '🥣', 'گرم', 50, 188, 6.5, 32, 3.5, array['gluten']::text[], '{}'::text[], 0.5, 1, 1.5, 2, 0.25, true, 13),
  ('whole_grain_toast', 'نان تست سبوس‌دار', 'starch', '🍞', 'برش', 30, 70, 3, 12, 1, array['gluten']::text[], '{}'::text[], 1, 2, 3, 4, 1, true, 14),
  ('sangak_bread', 'نان سنگک', 'starch', '🫓', 'گرم', 50, 129, 3.85, 28.7, 0.35, array['gluten']::text[], '{}'::text[], 0.5, 2, 2.5, 3, 0.5, true, 15),
  ('boiled_potato', 'سیب‌زمینی آب‌پز', 'starch', '🥔', 'گرم', 100, 87, 2, 20, 0.1, '{}'::text[], '{}'::text[], 0.5, 2, 3, 3.5, 0.25, true, 16),
  ('mixed_salad', 'سالاد سبزیجات', 'vegetable', '🥗', 'کاسه', 150, 30, 1.5, 6, 0.2, '{}'::text[], '{}'::text[], 0.5, 1, 1.5, 2, 0.5, true, 17),
  ('fresh_cucumber_tomato', 'خیار و گوجه تازه', 'vegetable', '🥒', 'گرم', 150, 25, 1.2, 5.6, 0.2, '{}'::text[], '{}'::text[], 0.5, 1, 1.5, 2, 0.5, true, 18),
  ('steamed_vegetables', 'سبزیجات بخارپز', 'vegetable', '🥦', 'گرم', 100, 30, 2, 6, 0.2, '{}'::text[], '{}'::text[], 0.5, 1.5, 2.5, 3, 0.5, true, 19),
  ('spinach_borani', 'بورانی اسفناج', 'vegetable', '🥬', 'گرم', 100, 73, 3, 6, 4, array['dairy']::text[], '{}'::text[], 0.5, 1, 1.5, 2, 0.5, true, 20),
  ('olive_oil', 'روغن زیتون', 'fat', '🫒', 'قاشق', 14, 119, 0, 0, 14, '{}'::text[], '{}'::text[], 0.25, 0.5, 1.25, 2, 0.25, true, 21),
  ('walnut', 'گردو', 'fat', '🌰', 'عدد', 6, 39, 0.9, 0.8, 3.9, array['tree_nut']::text[], '{}'::text[], 1, 2, 4, 6, 1, true, 22),
  ('mixed_nuts', 'آجیل خام بدون بادام‌زمینی', 'fat', '🥜', 'گرم', 25, 157, 5, 5, 13, array['tree_nut']::text[], '{}'::text[], 0.25, 0.75, 1, 1.5, 0.25, true, 23),
  ('avocado_half', 'آووکادو', 'fat', '🥑', 'عدد', 75, 120, 1.5, 6, 11, '{}'::text[], '{}'::text[], 0.5, 1, 1.5, 2, 0.5, true, 24),
  ('low_fat_cheese', 'پنیر کم‌چرب', 'dairy', '🧀', 'گرم', 30, 46, 6, 1, 2, array['dairy']::text[], array['vegan']::text[], 0.5, 1, 1.5, 2, 0.5, true, 25),
  ('low_fat_milk', 'شیر کم‌چرب', 'dairy', '🥛', 'لیوان', 250, 102, 8, 12, 2, array['dairy']::text[], array['vegan']::text[], 0.5, 1, 1, 1.2, 0.1, true, 26),
  ('low_fat_yogurt', 'ماست کم‌چرب', 'dairy', '🥣', 'گرم', 100, 45, 5, 6, 0.5, array['dairy']::text[], array['vegan']::text[], 0.5, 1.5, 2, 2.5, 0.5, true, 27),
  ('apple', 'سیب', 'fruit', '🍎', 'عدد', 150, 78, 0.4, 21, 0.3, '{}'::text[], '{}'::text[], 0.5, 1, 1.5, 2, 0.5, true, 28),
  ('banana', 'موز', 'fruit', '🍌', 'عدد', 120, 107, 1.3, 27, 0.4, '{}'::text[], '{}'::text[], 0.5, 1, 1.5, 2, 0.5, true, 29),
  ('medjool_date', 'خرمای مدجول', 'fruit', '🌴', 'عدد', 24, 67, 0.4, 18, 0.04, '{}'::text[], '{}'::text[], 1, 2, 2, 3, 1, true, 30)
on conflict (id) do update set
  name = excluded.name,
  role = excluded.role,
  emoji = excluded.emoji,
  unit_label = excluded.unit_label,
  grams_per_unit = excluded.grams_per_unit,
  kcal_per_unit = excluded.kcal_per_unit,
  protein_per_unit = excluded.protein_per_unit,
  carbs_per_unit = excluded.carbs_per_unit,
  fat_per_unit = excluded.fat_per_unit,
  allergy_flags = excluded.allergy_flags,
  excluded_for_vegetarian = excluded.excluded_for_vegetarian,
  portion_min_units = excluded.portion_min_units,
  portion_typical_units = excluded.portion_typical_units,
  portion_soft_max_units = excluded.portion_soft_max_units,
  portion_hard_max_units = excluded.portion_hard_max_units,
  portion_step = excluded.portion_step,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order;

-- Fiber + food-quality metadata. Fiber remains part of total carbohydrate
-- and is never added to carbs a second time.
update public.food_items as f
set
  fiber_g_per_unit = v.fiber_g_per_unit,
  quality_tags = v.quality_tags,
  fruit_veg_grams_per_unit = v.fruit_veg_grams_per_unit,
  fiber_source_name = v.fiber_source_name,
  fiber_source_url = v.fiber_source_url
from (values
  ('egg_white', 0, '{}'::text[], 0, 'USDA FoodData Central', 'https://fdc.nal.usda.gov/'),
  ('egg_whole', 0, array['whole_food']::text[], 0, 'USDA FoodData Central', 'https://fdc.nal.usda.gov/'),
  ('chicken_breast', 0, array['whole_food']::text[], 0, 'USDA FoodData Central', 'https://fdc.nal.usda.gov/'),
  ('grilled_fish', 0, array['whole_food']::text[], 0, 'USDA FoodData Central', 'https://fdc.nal.usda.gov/'),
  ('lean_beef', 0, array['whole_food']::text[], 0, 'USDA FoodData Central', 'https://fdc.nal.usda.gov/'),
  ('ground_beef_lean', 0, array['whole_food']::text[], 0, 'USDA FoodData Central', 'https://fdc.nal.usda.gov/'),
  ('whey_protein', 0, array['protein_supplement']::text[], 0, 'USDA FoodData Central / generic product profile', 'https://fdc.nal.usda.gov/'),
  ('pea_protein', 0.5, array['protein_supplement']::text[], 0, 'USDA FoodData Central / generic product profile', 'https://fdc.nal.usda.gov/'),
  ('soy_chunks', 13, array['legume']::text[], 0, 'USDA FoodData Central / textured soy profile', 'https://fdc.nal.usda.gov/'),
  ('lentils_cooked', 7.9, array['legume','whole_food']::text[], 0, 'USDA FoodData Central', 'https://fdc.nal.usda.gov/'),
  ('brown_rice_cooked', 1.8, array['whole_grain','whole_food']::text[], 0, 'USDA FoodData Central', 'https://fdc.nal.usda.gov/'),
  ('white_rice_cooked', 0.4, array['refined_grain']::text[], 0, 'USDA FoodData Central', 'https://fdc.nal.usda.gov/'),
  ('quinoa_cooked', 2.8, array['whole_grain','whole_food']::text[], 0, 'USDA FoodData Central', 'https://fdc.nal.usda.gov/'),
  ('oats_dry', 5.3, array['whole_grain','whole_food']::text[], 0, 'USDA FoodData Central', 'https://fdc.nal.usda.gov/'),
  ('whole_grain_toast', 2.0, array['whole_grain']::text[], 0, 'USDA FoodData Central / whole-wheat bread profile', 'https://fdc.nal.usda.gov/'),
  ('sangak_bread', 2.05, array['whole_grain']::text[], 0, 'Iranian carbohydrate composition study', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC7695225/'),
  ('boiled_potato', 1.8, array['starchy_vegetable','whole_food']::text[], 0, 'USDA FoodData Central', 'https://fdc.nal.usda.gov/'),
  ('mixed_salad', 3.0, array['non_starchy_vegetable','whole_food']::text[], 150, 'USDA FoodData Central / Behtan composite', 'https://fdc.nal.usda.gov/'),
  ('fresh_cucumber_tomato', 1.7, array['non_starchy_vegetable','whole_food']::text[], 150, 'USDA FoodData Central / Behtan composite', 'https://fdc.nal.usda.gov/'),
  ('steamed_vegetables', 3.0, array['non_starchy_vegetable','whole_food']::text[], 100, 'USDA FoodData Central / Behtan composite', 'https://fdc.nal.usda.gov/'),
  ('spinach_borani', 2.0, array['non_starchy_vegetable']::text[], 70, 'USDA FoodData Central / Behtan recipe estimate', 'https://fdc.nal.usda.gov/'),
  ('olive_oil', 0, array['unsaturated_fat']::text[], 0, 'USDA FoodData Central', 'https://fdc.nal.usda.gov/'),
  ('walnut', 0.4, array['nuts_seeds','unsaturated_fat','whole_food']::text[], 0, 'USDA FoodData Central', 'https://fdc.nal.usda.gov/'),
  ('mixed_nuts', 2.2, array['nuts_seeds','unsaturated_fat','whole_food']::text[], 0, 'USDA FoodData Central / mixed nuts profile', 'https://fdc.nal.usda.gov/'),
  ('avocado_half', 5.0, array['whole_fruit','unsaturated_fat','whole_food']::text[], 75, 'USDA FoodData Central', 'https://fdc.nal.usda.gov/'),
  ('low_fat_cheese', 0, '{}'::text[], 0, 'USDA FoodData Central / generic dairy profile', 'https://fdc.nal.usda.gov/'),
  ('low_fat_milk', 0, '{}'::text[], 0, 'USDA FoodData Central', 'https://fdc.nal.usda.gov/'),
  ('low_fat_yogurt', 0, '{}'::text[], 0, 'USDA FoodData Central / generic dairy profile', 'https://fdc.nal.usda.gov/'),
  ('apple', 3.6, array['whole_fruit','whole_food']::text[], 150, 'USDA FoodData Central', 'https://fdc.nal.usda.gov/'),
  ('banana', 3.1, array['whole_fruit','whole_food']::text[], 120, 'USDA FoodData Central', 'https://fdc.nal.usda.gov/'),
  ('medjool_date', 1.6, array['whole_fruit','whole_food']::text[], 24, 'USDA FoodData Central', 'https://fdc.nal.usda.gov/')
) as v(id, fiber_g_per_unit, quality_tags, fruit_veg_grams_per_unit, fiber_source_name, fiber_source_url)
where f.id = v.id;

delete from public.food_substitutes where food_item_id in ('brown_rice_cooked','white_rice_cooked','quinoa_cooked','boiled_potato','whole_grain_toast','sangak_bread','chicken_breast','grilled_fish','lean_beef','ground_beef_lean','whey_protein','pea_protein','egg_white','egg_whole','low_fat_milk','low_fat_yogurt','walnut','mixed_nuts','apple','banana','medjool_date');


-- Meal-aware food-swap metadata. This controls only what the swap UI may
-- OFFER in each meal; specialist meal templates can still use foods outside
-- these contexts when clinically/dietarily necessary.
update public.food_items as f
set
  swap_allowed_meals = v.allowed_meals,
  swap_group = v.swap_group,
  swap_priority = v.swap_priority
from (values
  ('egg_white', array['breakfast', 'dinner']::text[], 'egg', 20),
  ('egg_whole', array['breakfast', 'dinner']::text[], 'egg', 10),
  ('chicken_breast', array['lunch', 'afternoon_snack', 'dinner']::text[], 'main_protein', 10),
  ('grilled_fish', array['lunch', 'dinner']::text[], 'main_protein', 20),
  ('lean_beef', array['lunch', 'dinner']::text[], 'main_protein', 30),
  ('ground_beef_lean', array['lunch', 'dinner']::text[], 'main_protein', 35),
  ('whey_protein', array['morning_snack', 'afternoon_snack', 'night_snack']::text[], 'protein_supplement', 10),
  ('pea_protein', array['morning_snack', 'afternoon_snack', 'night_snack']::text[], 'protein_supplement', 20),
  ('soy_chunks', array['lunch', 'dinner']::text[], 'plant_protein', 20),
  ('lentils_cooked', array['breakfast', 'lunch', 'dinner']::text[], 'plant_protein', 10),
  ('brown_rice_cooked', array['lunch', 'dinner']::text[], 'grain_starch', 20),
  ('white_rice_cooked', array['lunch', 'dinner']::text[], 'grain_starch', 10),
  ('quinoa_cooked', array['lunch', 'dinner']::text[], 'grain_starch', 30),
  ('oats_dry', array['breakfast', 'morning_snack', 'afternoon_snack']::text[], 'breakfast_cereal', 10),
  ('whole_grain_toast', array['breakfast', 'morning_snack', 'afternoon_snack', 'dinner', 'night_snack']::text[], 'bread', 20),
  ('sangak_bread', array['breakfast', 'lunch', 'dinner']::text[], 'bread', 10),
  ('boiled_potato', array['lunch', 'afternoon_snack', 'dinner']::text[], 'potato_starch', 20),
  ('mixed_salad', array['lunch', 'dinner']::text[], 'vegetable', 20),
  ('fresh_cucumber_tomato', array['breakfast', 'lunch', 'dinner']::text[], 'vegetable', 10),
  ('steamed_vegetables', array['lunch', 'dinner']::text[], 'vegetable', 20),
  ('spinach_borani', array['lunch', 'dinner']::text[], 'vegetable', 30),
  ('olive_oil', array['lunch', 'dinner']::text[], 'oil', 10),
  ('walnut', array['breakfast', 'morning_snack', 'afternoon_snack', 'night_snack']::text[], 'nuts', 10),
  ('mixed_nuts', array['breakfast', 'morning_snack', 'afternoon_snack', 'night_snack']::text[], 'nuts', 20),
  ('avocado_half', array['breakfast', 'morning_snack', 'afternoon_snack', 'dinner']::text[], 'plant_fat', 20),
  ('low_fat_cheese', array['breakfast', 'morning_snack', 'dinner']::text[], 'dairy', 10),
  ('low_fat_milk', array['breakfast', 'morning_snack', 'afternoon_snack', 'night_snack']::text[], 'dairy', 20),
  ('low_fat_yogurt', array['lunch', 'afternoon_snack', 'dinner', 'night_snack']::text[], 'dairy', 15),
  ('apple', array['breakfast', 'morning_snack', 'afternoon_snack', 'night_snack']::text[], 'fruit', 10),
  ('banana', array['breakfast', 'morning_snack', 'afternoon_snack', 'night_snack']::text[], 'fruit', 20),
  ('medjool_date', array['breakfast', 'morning_snack', 'afternoon_snack', 'night_snack']::text[], 'fruit', 30)
) as v(id, allowed_meals, swap_group, swap_priority)
where f.id = v.id;

insert into public.food_substitutes (food_item_id, substitute_food_item_id, is_active) values
  ('brown_rice_cooked', 'white_rice_cooked', true),
  ('brown_rice_cooked', 'quinoa_cooked', true),
  ('brown_rice_cooked', 'boiled_potato', true),
  ('brown_rice_cooked', 'sangak_bread', true),
  ('white_rice_cooked', 'brown_rice_cooked', true),
  ('white_rice_cooked', 'quinoa_cooked', true),
  ('white_rice_cooked', 'boiled_potato', true),
  ('white_rice_cooked', 'sangak_bread', true),
  ('quinoa_cooked', 'brown_rice_cooked', true),
  ('quinoa_cooked', 'white_rice_cooked', true),
  ('quinoa_cooked', 'boiled_potato', true),
  ('quinoa_cooked', 'sangak_bread', true),
  ('boiled_potato', 'white_rice_cooked', true),
  ('boiled_potato', 'brown_rice_cooked', true),
  ('boiled_potato', 'quinoa_cooked', true),
  ('boiled_potato', 'sangak_bread', true),
  ('whole_grain_toast', 'sangak_bread', true),
  ('sangak_bread', 'whole_grain_toast', true),
  ('sangak_bread', 'white_rice_cooked', true),
  ('sangak_bread', 'boiled_potato', true),
  ('chicken_breast', 'grilled_fish', true),
  ('chicken_breast', 'lean_beef', true),
  ('chicken_breast', 'ground_beef_lean', true),
  ('grilled_fish', 'chicken_breast', true),
  ('grilled_fish', 'lean_beef', true),
  ('lean_beef', 'chicken_breast', true),
  ('lean_beef', 'grilled_fish', true),
  ('lean_beef', 'ground_beef_lean', true),
  ('ground_beef_lean', 'lean_beef', true),
  ('ground_beef_lean', 'chicken_breast', true),
  ('whey_protein', 'pea_protein', true),
  ('pea_protein', 'whey_protein', true),
  ('egg_white', 'egg_whole', true),
  ('egg_whole', 'egg_white', true),
  ('low_fat_milk', 'low_fat_yogurt', true),
  ('low_fat_yogurt', 'low_fat_milk', true),
  ('walnut', 'mixed_nuts', true),
  ('walnut', 'avocado_half', true),
  ('mixed_nuts', 'walnut', true),
  ('mixed_nuts', 'avocado_half', true),
  ('apple', 'banana', true),
  ('apple', 'medjool_date', true),
  ('banana', 'apple', true),
  ('banana', 'medjool_date', true),
  ('medjool_date', 'banana', true),
  ('medjool_date', 'apple', true)
on conflict (food_item_id, substitute_food_item_id) do update set is_active = excluded.is_active;

insert into public.meal_templates (
  id, slot, display_name, is_workout_day_only, is_rest_day_only, max_per_week, restricted_diet_only, vegetarian_statuses_only, goal_tags, is_active, sort_order
) values
  ('bk_sangak_cheese_walnut', 'breakfast', 'نان سنگک، پنیر، گردو و خیار و گوجه', false, false, null, false, '{}'::text[], '{}'::text[], true, 0),
  ('bk_eggs_sangak', 'breakfast', 'تخم‌مرغ با نان سنگک و خیار و گوجه', false, false, null, false, '{}'::text[], '{}'::text[], true, 1),
  ('bk_mixed_eggs_sangak', 'breakfast', 'تخم‌مرغ و سفیده با نان سنگک', false, false, null, false, '{}'::text[], '{}'::text[], true, 2),
  ('bk_adasi_sangak', 'breakfast', 'عدسی با نان سنگک و خیار و گوجه', false, false, null, false, '{}'::text[], '{}'::text[], true, 3),
  ('bk_vegan_lentil_pea', 'breakfast', 'عدسی با نوشیدنی پروتئین گیاهی و خیار و گوجه', false, false, null, true, array['vegan']::text[], '{}'::text[], true, 4),
  ('bk_restricted_eggs_potato', 'breakfast', 'تخم‌مرغ با سیب‌زمینی آب‌پز و خیار و گوجه', false, false, null, true, '{}'::text[], '{}'::text[], true, 5),
  ('bk_restricted_lentil_potato', 'breakfast', 'عدسی با سیب‌زمینی آب‌پز و خیار و گوجه', false, false, null, true, '{}'::text[], '{}'::text[], true, 6),
  ('ms_whey_milk', 'morning_snack', 'پروتئین وی با شیر کم‌چرب', true, false, null, false, '{}'::text[], '{}'::text[], true, 7),
  ('ms_lentil_apple', 'morning_snack', 'عدسی و سیب', false, false, null, false, '{}'::text[], '{}'::text[], true, 8),
  ('ms_pea_apple', 'morning_snack', 'پروتئین نخود و سیب', false, false, null, false, '{}'::text[], '{}'::text[], true, 9),
  ('ms_dates_milk', 'morning_snack', 'خرما با شیر کم‌چرب', false, false, null, false, '{}'::text[], '{}'::text[], true, 10),
  ('ms_dates', 'morning_snack', 'خرمای مدجول', false, false, null, false, '{}'::text[], '{}'::text[], true, 11),
  ('ms_banana_dates', 'morning_snack', 'موز و خرما', false, false, null, false, '{}'::text[], '{}'::text[], true, 12),
  ('ms_toast_banana', 'morning_snack', 'نان تست سبوس‌دار و موز', false, false, null, false, '{}'::text[], '{}'::text[], true, 13),
  ('ln_chicken_rice_yogurt', 'lunch', 'مرغ با برنج، سالاد و ماست', false, false, null, false, '{}'::text[], '{}'::text[], true, 14),
  ('ln_fish_rice_salad', 'lunch', 'ماهی کبابی با برنج و سالاد', false, false, null, false, '{}'::text[], '{}'::text[], true, 15),
  ('ln_beef_rice_salad', 'lunch', 'گوشت کم‌چرب با برنج و سالاد', false, false, null, false, '{}'::text[], '{}'::text[], true, 16),
  ('ln_adas_polo_beef', 'lunch', 'عدس‌پلو با گوشت کم‌چرب و سالاد', false, false, null, false, '{}'::text[], '{}'::text[], true, 17),
  ('ln_vegan_pea_lentil_rice', 'lunch', 'عدس‌پلو سبک با نوشیدنی پروتئین گیاهی', false, false, null, true, array['vegan']::text[], '{}'::text[], true, 18),
  ('ln_vegan_soy_rice', 'lunch', 'سویا با برنج و سالاد', false, false, null, true, array['vegan','lacto_ovo']::text[], '{}'::text[], true, 19),
  ('ln_adas_polo_vegan', 'lunch', 'عدس‌پلو با سالاد', false, false, null, false, '{}'::text[], '{}'::text[], true, 20),
  ('as_potato_chicken', 'afternoon_snack', 'سیب‌زمینی و فیله مرغ', true, false, null, false, '{}'::text[], '{}'::text[], true, 21),
  ('as_whey_nuts', 'afternoon_snack', 'پروتئین وی و آجیل', false, true, null, false, '{}'::text[], '{}'::text[], true, 22),
  ('as_potato_lentil', 'afternoon_snack', 'سیب‌زمینی و عدسی', false, false, null, false, '{}'::text[], '{}'::text[], true, 23),
  ('as_pea_potato', 'afternoon_snack', 'پروتئین نخود و سیب‌زمینی', false, false, null, false, '{}'::text[], '{}'::text[], true, 24),
  ('as_potato_dates', 'afternoon_snack', 'سیب‌زمینی و خرما', false, false, null, false, '{}'::text[], '{}'::text[], true, 25),
  ('as_banana_dates', 'afternoon_snack', 'موز و خرما', false, false, null, false, '{}'::text[], '{}'::text[], true, 26),
  ('as_banana_dates_avocado', 'afternoon_snack', 'موز، خرما و آووکادو', false, false, null, false, '{}'::text[], '{}'::text[], true, 27),
  ('as_toast_dates', 'afternoon_snack', 'نان تست سبوس‌دار و خرما', false, false, null, false, '{}'::text[], '{}'::text[], true, 28),
  ('dn_eggs_sangak', 'dinner', 'تخم‌مرغ با نان سنگک و خیار و گوجه', false, false, null, false, '{}'::text[], '{}'::text[], true, 29),
  ('dn_chicken_sangak', 'dinner', 'مرغ با نان سنگک، سالاد و ماست', false, false, null, false, '{}'::text[], '{}'::text[], true, 30),
  ('dn_adasi_sangak', 'dinner', 'عدسی با نان سنگک و خیار و گوجه', false, false, null, false, '{}'::text[], '{}'::text[], true, 31),
  ('dn_fish_potato_salad', 'dinner', 'ماهی کبابی با سیب‌زمینی و سالاد', false, false, null, false, '{}'::text[], '{}'::text[], true, 32),
  ('dn_vegan_pea_lentil_potato', 'dinner', 'عدسی سبک با سیب‌زمینی و نوشیدنی پروتئین گیاهی', false, false, null, true, array['vegan']::text[], '{}'::text[], true, 33),
  ('dn_vegan_soy_potato', 'dinner', 'سویا با سیب‌زمینی آب‌پز و سالاد', false, false, null, true, array['vegan','lacto_ovo']::text[], '{}'::text[], true, 34),
  ('dn_restricted_chicken_potato', 'dinner', 'مرغ با سیب‌زمینی آب‌پز، سالاد و ماست', false, false, null, true, '{}'::text[], '{}'::text[], true, 35),
  ('dn_restricted_lentil_potato', 'dinner', 'عدسی با سیب‌زمینی آب‌پز و سالاد', false, false, null, true, '{}'::text[], '{}'::text[], true, 36),
  ('ns_milk', 'night_snack', 'شیر کم‌چرب', false, false, null, false, '{}'::text[], '{}'::text[], true, 37),
  ('ns_apple', 'night_snack', 'سیب', false, false, null, false, '{}'::text[], '{}'::text[], true, 38),
  ('ns_pea', 'night_snack', 'نیم‌اسکوپ پروتئین نخود', false, false, null, false, '{}'::text[], '{}'::text[], true, 39),
  ('ns_dates', 'night_snack', 'خرمای مدجول', false, false, null, false, '{}'::text[], '{}'::text[], true, 40),
  ('ns_banana_dates', 'night_snack', 'موز و خرما', false, false, null, false, '{}'::text[], '{}'::text[], true, 41),
  ('ns_toast_dates', 'night_snack', 'نان تست سبوس‌دار و خرما', false, false, null, false, '{}'::text[], '{}'::text[], true, 42)
on conflict (id) do update set
  slot = excluded.slot,
  display_name = excluded.display_name,
  is_workout_day_only = excluded.is_workout_day_only,
  is_rest_day_only = excluded.is_rest_day_only,
  max_per_week = excluded.max_per_week,
  restricted_diet_only = excluded.restricted_diet_only,
  vegetarian_statuses_only = excluded.vegetarian_statuses_only,
  goal_tags = excluded.goal_tags,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order;

delete from public.meal_template_slots where template_id in ('bk_sangak_cheese_walnut','bk_eggs_sangak','bk_mixed_eggs_sangak','bk_adasi_sangak','bk_vegan_lentil_pea','bk_restricted_eggs_potato','bk_restricted_lentil_potato','ms_whey_milk','ms_lentil_apple','ms_pea_apple','ms_dates_milk','ms_dates','ms_banana_dates','ms_toast_banana','ln_chicken_rice_yogurt','ln_fish_rice_salad','ln_beef_rice_salad','ln_adas_polo_beef','ln_vegan_pea_lentil_rice','ln_vegan_soy_rice','ln_adas_polo_vegan','as_potato_chicken','as_whey_nuts','as_potato_lentil','as_pea_potato','as_potato_dates','as_banana_dates','as_banana_dates_avocado','as_toast_dates','dn_eggs_sangak','dn_chicken_sangak','dn_adasi_sangak','dn_fish_potato_salad','dn_vegan_pea_lentil_potato','dn_vegan_soy_potato','dn_restricted_chicken_potato','dn_restricted_lentil_potato','ns_milk','ns_apple','ns_pea','ns_dates','ns_banana_dates','ns_toast_dates');

insert into public.meal_template_slots (template_id, position, role, primary_food_item_id, dynamic_units, fixed_units) values
  ('bk_sangak_cheese_walnut', 0, 'starch', 'sangak_bread', true, null),
  ('bk_sangak_cheese_walnut', 1, 'dairy', 'low_fat_cheese', true, null),
  ('bk_sangak_cheese_walnut', 2, 'fat', 'walnut', true, null),
  ('bk_sangak_cheese_walnut', 3, 'vegetable', 'fresh_cucumber_tomato', false, 1),
  ('bk_eggs_sangak', 0, 'protein', 'egg_whole', true, null),
  ('bk_eggs_sangak', 1, 'starch', 'sangak_bread', true, null),
  ('bk_eggs_sangak', 2, 'vegetable', 'fresh_cucumber_tomato', false, 1),
  ('bk_mixed_eggs_sangak', 0, 'protein', 'egg_whole', true, null),
  ('bk_mixed_eggs_sangak', 1, 'protein', 'egg_white', true, null),
  ('bk_mixed_eggs_sangak', 2, 'starch', 'sangak_bread', true, null),
  ('bk_mixed_eggs_sangak', 3, 'vegetable', 'fresh_cucumber_tomato', false, 1),
  ('bk_adasi_sangak', 0, 'protein', 'lentils_cooked', true, null),
  ('bk_adasi_sangak', 1, 'starch', 'sangak_bread', true, null),
  ('bk_adasi_sangak', 2, 'vegetable', 'fresh_cucumber_tomato', false, 1),
  ('bk_vegan_lentil_pea', 0, 'protein', 'lentils_cooked', true, null),
  ('bk_vegan_lentil_pea', 1, 'protein', 'pea_protein', true, null),
  ('bk_vegan_lentil_pea', 2, 'vegetable', 'fresh_cucumber_tomato', false, 1),
  ('bk_vegan_lentil_pea', 3, 'fat', 'olive_oil', true, null),
  ('bk_restricted_eggs_potato', 0, 'protein', 'egg_whole', true, null),
  ('bk_restricted_eggs_potato', 1, 'starch', 'boiled_potato', true, null),
  ('bk_restricted_eggs_potato', 2, 'dairy', 'low_fat_cheese', true, null),
  ('bk_restricted_eggs_potato', 3, 'vegetable', 'fresh_cucumber_tomato', false, 1),
  ('bk_restricted_lentil_potato', 0, 'protein', 'lentils_cooked', true, null),
  ('bk_restricted_lentil_potato', 1, 'starch', 'boiled_potato', true, null),
  ('bk_restricted_lentil_potato', 2, 'vegetable', 'fresh_cucumber_tomato', false, 1),
  ('bk_restricted_lentil_potato', 3, 'fat', 'olive_oil', true, null),
  ('ms_whey_milk', 0, 'protein', 'whey_protein', true, null),
  ('ms_whey_milk', 1, 'dairy', 'low_fat_milk', false, 1),
  ('ms_lentil_apple', 0, 'protein', 'lentils_cooked', true, null),
  ('ms_lentil_apple', 1, 'fruit', 'apple', false, 1),
  ('ms_pea_apple', 0, 'protein', 'pea_protein', true, null),
  ('ms_pea_apple', 1, 'fruit', 'apple', false, 1),
  ('ms_dates_milk', 0, 'fruit', 'medjool_date', true, null),
  ('ms_dates_milk', 1, 'dairy', 'low_fat_milk', true, null),
  ('ms_dates', 0, 'fruit', 'medjool_date', true, null),
  ('ms_banana_dates', 0, 'fruit', 'banana', true, null),
  ('ms_banana_dates', 1, 'fruit', 'medjool_date', true, null),
  ('ms_toast_banana', 0, 'starch', 'whole_grain_toast', true, null),
  ('ms_toast_banana', 1, 'fruit', 'banana', true, null),
  ('ln_chicken_rice_yogurt', 0, 'protein', 'chicken_breast', true, null),
  ('ln_chicken_rice_yogurt', 1, 'starch', 'white_rice_cooked', true, null),
  ('ln_chicken_rice_yogurt', 2, 'vegetable', 'mixed_salad', false, 1),
  ('ln_chicken_rice_yogurt', 3, 'fat', 'olive_oil', true, null),
  ('ln_chicken_rice_yogurt', 4, 'dairy', 'low_fat_yogurt', true, null),
  ('ln_fish_rice_salad', 0, 'protein', 'grilled_fish', true, null),
  ('ln_fish_rice_salad', 1, 'starch', 'white_rice_cooked', true, null),
  ('ln_fish_rice_salad', 2, 'vegetable', 'mixed_salad', false, 1),
  ('ln_fish_rice_salad', 3, 'fat', 'olive_oil', true, null),
  ('ln_beef_rice_salad', 0, 'protein', 'ground_beef_lean', true, null),
  ('ln_beef_rice_salad', 1, 'starch', 'white_rice_cooked', true, null),
  ('ln_beef_rice_salad', 2, 'vegetable', 'mixed_salad', false, 1),
  ('ln_beef_rice_salad', 3, 'fat', 'olive_oil', true, null),
  ('ln_beef_rice_salad', 4, 'dairy', 'low_fat_yogurt', true, null),
  ('ln_adas_polo_beef', 0, 'protein', 'ground_beef_lean', true, null),
  ('ln_adas_polo_beef', 1, 'protein', 'lentils_cooked', true, null),
  ('ln_adas_polo_beef', 2, 'starch', 'white_rice_cooked', true, null),
  ('ln_adas_polo_beef', 3, 'vegetable', 'mixed_salad', false, 1),
  ('ln_vegan_pea_lentil_rice', 0, 'protein', 'pea_protein', true, null),
  ('ln_vegan_pea_lentil_rice', 1, 'protein', 'lentils_cooked', true, null),
  ('ln_vegan_pea_lentil_rice', 2, 'starch', 'white_rice_cooked', true, null),
  ('ln_vegan_pea_lentil_rice', 3, 'vegetable', 'mixed_salad', false, 1),
  ('ln_vegan_pea_lentil_rice', 4, 'fat', 'olive_oil', true, null),
  ('ln_vegan_soy_rice', 0, 'protein', 'soy_chunks', true, null),
  ('ln_vegan_soy_rice', 1, 'starch', 'white_rice_cooked', true, null),
  ('ln_vegan_soy_rice', 2, 'vegetable', 'mixed_salad', false, 1),
  ('ln_vegan_soy_rice', 3, 'fat', 'olive_oil', true, null),
  ('ln_adas_polo_vegan', 0, 'protein', 'lentils_cooked', true, null),
  ('ln_adas_polo_vegan', 1, 'starch', 'white_rice_cooked', true, null),
  ('ln_adas_polo_vegan', 2, 'vegetable', 'mixed_salad', false, 1),
  ('ln_adas_polo_vegan', 3, 'fat', 'olive_oil', true, null),
  ('as_potato_chicken', 0, 'starch', 'boiled_potato', true, null),
  ('as_potato_chicken', 1, 'protein', 'chicken_breast', true, null),
  ('as_whey_nuts', 0, 'protein', 'whey_protein', true, null),
  ('as_whey_nuts', 1, 'fat', 'mixed_nuts', false, 0.5),
  ('as_potato_lentil', 0, 'starch', 'boiled_potato', true, null),
  ('as_potato_lentil', 1, 'protein', 'lentils_cooked', true, null),
  ('as_potato_lentil', 2, 'fat', 'olive_oil', false, 0.25),
  ('as_pea_potato', 0, 'protein', 'pea_protein', true, null),
  ('as_pea_potato', 1, 'starch', 'boiled_potato', true, null),
  ('as_potato_dates', 0, 'starch', 'boiled_potato', true, null),
  ('as_potato_dates', 1, 'fruit', 'medjool_date', true, null),
  ('as_banana_dates', 0, 'fruit', 'banana', true, null),
  ('as_banana_dates', 1, 'fruit', 'medjool_date', true, null),
  ('as_banana_dates_avocado', 0, 'fruit', 'banana', true, null),
  ('as_banana_dates_avocado', 1, 'fruit', 'medjool_date', true, null),
  ('as_banana_dates_avocado', 2, 'fat', 'avocado_half', true, null),
  ('as_toast_dates', 0, 'starch', 'whole_grain_toast', true, null),
  ('as_toast_dates', 1, 'fruit', 'medjool_date', true, null),
  ('dn_eggs_sangak', 0, 'protein', 'egg_whole', true, null),
  ('dn_eggs_sangak', 1, 'starch', 'sangak_bread', true, null),
  ('dn_eggs_sangak', 2, 'vegetable', 'fresh_cucumber_tomato', false, 1),
  ('dn_chicken_sangak', 0, 'protein', 'chicken_breast', true, null),
  ('dn_chicken_sangak', 1, 'starch', 'sangak_bread', true, null),
  ('dn_chicken_sangak', 2, 'vegetable', 'mixed_salad', false, 1),
  ('dn_chicken_sangak', 3, 'fat', 'olive_oil', true, null),
  ('dn_chicken_sangak', 4, 'dairy', 'low_fat_yogurt', true, null),
  ('dn_adasi_sangak', 0, 'protein', 'lentils_cooked', true, null),
  ('dn_adasi_sangak', 1, 'starch', 'sangak_bread', true, null),
  ('dn_adasi_sangak', 2, 'vegetable', 'fresh_cucumber_tomato', false, 1),
  ('dn_adasi_sangak', 3, 'fat', 'olive_oil', true, null),
  ('dn_fish_potato_salad', 0, 'protein', 'grilled_fish', true, null),
  ('dn_fish_potato_salad', 1, 'starch', 'boiled_potato', true, null),
  ('dn_fish_potato_salad', 2, 'vegetable', 'mixed_salad', false, 1),
  ('dn_fish_potato_salad', 3, 'fat', 'olive_oil', true, null),
  ('dn_vegan_pea_lentil_potato', 0, 'protein', 'pea_protein', true, null),
  ('dn_vegan_pea_lentil_potato', 1, 'protein', 'lentils_cooked', true, null),
  ('dn_vegan_pea_lentil_potato', 2, 'starch', 'boiled_potato', true, null),
  ('dn_vegan_pea_lentil_potato', 3, 'vegetable', 'mixed_salad', false, 1),
  ('dn_vegan_pea_lentil_potato', 4, 'fat', 'olive_oil', true, null),
  ('dn_vegan_soy_potato', 0, 'protein', 'soy_chunks', true, null),
  ('dn_vegan_soy_potato', 1, 'starch', 'boiled_potato', true, null),
  ('dn_vegan_soy_potato', 2, 'vegetable', 'mixed_salad', false, 1),
  ('dn_vegan_soy_potato', 3, 'fat', 'olive_oil', true, null),
  ('dn_restricted_chicken_potato', 0, 'protein', 'chicken_breast', true, null),
  ('dn_restricted_chicken_potato', 1, 'starch', 'boiled_potato', true, null),
  ('dn_restricted_chicken_potato', 2, 'vegetable', 'mixed_salad', false, 1),
  ('dn_restricted_chicken_potato', 3, 'fat', 'olive_oil', true, null),
  ('dn_restricted_chicken_potato', 4, 'dairy', 'low_fat_yogurt', true, null),
  ('dn_restricted_lentil_potato', 0, 'protein', 'lentils_cooked', true, null),
  ('dn_restricted_lentil_potato', 1, 'starch', 'boiled_potato', true, null),
  ('dn_restricted_lentil_potato', 2, 'vegetable', 'mixed_salad', false, 1),
  ('dn_restricted_lentil_potato', 3, 'fat', 'olive_oil', true, null),
  ('ns_milk', 0, 'dairy', 'low_fat_milk', true, null),
  ('ns_apple', 0, 'fruit', 'apple', true, null),
  ('ns_pea', 0, 'protein', 'pea_protein', true, null),
  ('ns_dates', 0, 'fruit', 'medjool_date', true, null),
  ('ns_banana_dates', 0, 'fruit', 'banana', true, null),
  ('ns_banana_dates', 1, 'fruit', 'medjool_date', true, null),
  ('ns_toast_dates', 0, 'starch', 'whole_grain_toast', true, null),
  ('ns_toast_dates', 1, 'fruit', 'medjool_date', true, null);

commit;
