import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';
const db = new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create table auth.users(id uuid primary key,phone text,email text,phone_confirmed_at timestamptz,created_at timestamptz default now(),last_sign_in_at timestamptz);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth to authenticated; grant execute on function auth.uid() to authenticated;`);
let schema = await readFile(new URL('../supabase/schema.sql',import.meta.url),'utf8');
await db.exec(schema.replace('create extension if not exists "uuid-ossp";',''));
if (!schema.includes('create table public.billing_settings')) await db.exec(await readFile(new URL('../supabase/migrations/20260907_014_zarinpal_billing.sql', import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20260915_016_admin_console.sql',import.meta.url),'utf8'));
const admin=randomUUID(),user=randomUUID(),other=randomUUID();
await db.query('insert into auth.users(id,phone,phone_confirmed_at) values($1,\'989111111111\',now()),($2,\'989122222222\',now()),($3,\'989133333333\',null)',[admin,user,other]);
await db.query('insert into admin_members(user_id) values($1),($2)',[admin,other]);
await db.exec("update billing_settings set mode='live',checkout_enabled=true");
const asUser = async id => { await db.exec('reset role'); await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]); await db.exec('set role authenticated'); };
const rpc = async (name,args=[]) => (await db.query(`select public.${name}(${args.map((_,i)=>`$${i+1}`).join(',')}) as result`,args)).rows[0].result;
await asUser(user);
assert.equal(await rpc('admin_allowed'),false);
for(const [name,args] of [['admin_overview',[]],['admin_user_detail',[user]],['admin_payments',[]],['admin_change_subscription',[randomUUID(),user,'grant',null,'gold',new Date(Date.now()+86400000).toISOString(),null,'testing']]]) await assert.rejects(()=>rpc(name,args),/ADMIN_REQUIRED/);
for(const table of ['admin_members','admin_audit_log','daily_plan_snapshots','user_subscriptions']) await assert.rejects(()=>db.exec(`select * from ${table}`),/permission denied/);
await assert.rejects(()=>db.query('insert into admin_members(user_id) values($1)',[user]),/permission denied/);
await asUser(other); assert.equal(await rpc('admin_allowed'),false,'Unverified allowlisted user denied');
await asUser(admin); assert.equal(await rpc('admin_allowed'),true);
assert.equal((await rpc('admin_overview')).stats.users,3);
const expiry=new Date(Date.now()+86400000).toISOString(),request=randomUUID();
const args=[request,user,'grant',null,'gold',expiry,null,'هدیه پشتیبانی'];
const sub=await rpc('admin_change_subscription',args);
assert.equal(sub.grant_source,'admin'); assert.equal(sub.source_order_id,null);
assert.equal((await rpc('admin_change_subscription',args)).id,sub.id,'Retry idempotent');
assert.equal((await rpc('admin_overview')).stats.revenue_toman,0,'Manual grant is not revenue');
await assert.rejects(()=>rpc('admin_change_subscription',[randomUUID(),user,'grant',null,'gold',expiry,null,'duplicate']),/ALREADY_ACTIVE/);
await assert.rejects(()=>rpc('admin_change_subscription',[randomUUID(),user,'expiry',sub.id,'gold',expiry,null,'stale']),/STALE_SUBSCRIPTION/);
const extended=await rpc('admin_change_subscription',[randomUUID(),user,'expiry',sub.id,'gold',new Date(Date.now()+2*86400000).toISOString(),sub.expires_at,'تمدید دستی']);
assert.notEqual(extended.expires_at,sub.expires_at);
await asUser(user); assert.equal(await rpc('billing_has_access'),true);
const today=new Date().toISOString().slice(0,10);
const snapshot={schemaVersion:1,targets:{targetCalories:2000},plan:{meals:[{slot:'lunch'}]}};
await rpc('save_daily_plan',[today,snapshot]);
await rpc('save_daily_plan',[today,snapshot]);
await assert.rejects(()=>rpc('save_daily_plan',['2020-01-01',snapshot]),/INVALID_SNAPSHOT/);
await assert.rejects(()=>rpc('save_daily_plan',[today,{schemaVersion:1}]),/INVALID_SNAPSHOT/);
await asUser(admin);
let detail=await rpc('admin_user_detail',[user,today]);
assert.equal(detail.saved_plan.revision,1); assert.equal(detail.audit.length,2);
assert.equal((await rpc('admin_user_detail',[other,today])).saved_plan,null,'No other user overwritten');
await rpc('admin_change_subscription',[randomUUID(),user,'revoke',sub.id,'gold',null,extended.expires_at,'قطع آزمایشی']);
await asUser(user); assert.equal(await rpc('billing_has_access'),false);
await assert.rejects(()=>rpc('save_daily_plan',[today,snapshot]),/ACCESS_DENIED/);
await db.exec('reset role');
// Verify the existing paid-settlement path still works with the new source constraint.
const paidOrder=await rpc('billing_begin_order',[other,'gold',249000,30]);
await db.query("update payment_orders set status='pending',authority='A-admin-regression' where id=$1",[paidOrder.id]);
await asUser(admin);
await assert.rejects(()=>rpc('admin_change_subscription',[randomUUID(),other,'grant',null,'gold',expiry,null,'pending guard']),/PENDING_ORDER_EXISTS/);
await db.exec('reset role');
await rpc('billing_claim_verify',[paidOrder.id]);
const paidSub=await rpc('billing_settle',[paidOrder.id,'9991234567',100]);
assert.equal(paidSub.grant_source,'payment'); assert.equal(paidSub.source_order_id,paidOrder.id);
await asUser(admin); assert.equal((await rpc('admin_overview')).stats.revenue_toman,249000);
assert.equal((await rpc('admin_payments')).length,1);
await db.exec('reset role'); await db.query('delete from admin_members where user_id=$1',[admin]);
await asUser(admin); await assert.rejects(()=>rpc('admin_overview'),/ADMIN_REQUIRED/);
await db.exec('reset role;set role anon'); await assert.rejects(()=>rpc('admin_allowed'),/permission denied/);
await db.close();
console.log('✅ Admin SQL: allowlist + verified phone, denied non-admin/anonymous access, no self-promotion, manual grant, idempotency, stale edit guard, audit, snapshot ownership, expiry/revocation and revenue isolation');
