begin;
alter table public.meal_templates drop constraint if exists meal_templates_slot_check;
alter table public.meal_templates add constraint meal_templates_slot_check check(slot in ('breakfast','morning_snack','lunch','afternoon_snack','dinner','night_snack','post_workout'));
alter table public.daily_meal_checkins drop constraint if exists daily_meal_checkins_meal_slot_check;
alter table public.daily_meal_checkins add constraint daily_meal_checkins_meal_slot_check check(meal_slot in ('breakfast','morning_snack','lunch','afternoon_snack','dinner','night_snack','post_workout'));
-- Small-date proxy: USDA Deglet Noor, 8.3 g edible portion; not a laboratory value for all Iranian cultivars.
insert into public.food_items(id,name,role,emoji,unit_label,grams_per_unit,kcal_per_unit,protein_per_unit,carbs_per_unit,fat_per_unit,fiber_g_per_unit,quality_tags,fruit_veg_grams_per_unit,allergy_flags,excluded_for_vegetarian,portion_min_units,portion_typical_units,portion_soft_max_units,portion_hard_max_units,portion_step,swap_allowed_meals,swap_group,swap_priority,source_name,source_url)
values('dates_small','خرمای معمولی کوچک','fruit','🌴','عدد',8.3,23.41,.2,6.23,.03,.66,array['whole_fruit','whole_food'],8.3,'{}','{}',1,2,3,4,1,array['breakfast','morning_snack','afternoon_snack','night_snack'],'dried_fruit',30,'USDA Deglet Noor proxy (8.3g); Iranian variety may differ','https://www.uhhospitals.org/health-information/health-and-wellness-library/article/nutritionfacts-v1/dates-deglet-noor-1-date') on conflict(id) do nothing;
update public.meal_template_slots set primary_food_item_id='dates_small' where primary_food_item_id='medjool_date';
insert into public.food_substitutes(food_item_id,substitute_food_item_id)
select case when food_item_id='medjool_date' then 'dates_small' else food_item_id end,case when substitute_food_item_id='medjool_date' then 'dates_small' else substitute_food_item_id end from public.food_substitutes where food_item_id='medjool_date' or substitute_food_item_id='medjool_date' on conflict do nothing;
update public.food_substitutes set is_active=false where food_item_id='medjool_date' or substitute_food_item_id='medjool_date';
update public.food_items set is_active=false where id='medjool_date';
update public.food_items set swap_group='fresh_fruit' where id in ('apple','banana');
update public.meal_templates set is_active=false where id in ('as_potato_chicken','as_whey_nuts','as_potato_lentil','as_pea_potato','as_potato_dates','as_banana_dates','as_banana_dates_avocado','as_toast_dates','balanced_afternoon_snack_banana_whole_toast');
insert into public.meal_templates(id,slot,display_name,is_workout_day_only,is_rest_day_only,restricted_diet_only,goal_tags,is_active,sort_order) values('bk_mixed_eggs_sangak','breakfast','تخم‌مرغ، پنیر و نان سنگک',false,false,false,'{}',true,210) on conflict(id) do update set display_name=excluded.display_name,is_active=true;
delete from public.meal_template_slots where template_id='bk_mixed_eggs_sangak';
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('bk_mixed_eggs_sangak',0,'protein','egg_whole',true,null);
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('bk_mixed_eggs_sangak',1,'protein','egg_white',true,null);
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('bk_mixed_eggs_sangak',2,'dairy','low_fat_cheese',true,null);
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('bk_mixed_eggs_sangak',3,'starch','sangak_bread',true,null);
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('bk_mixed_eggs_sangak',4,'vegetable','fresh_cucumber_tomato',false,1);
insert into public.meal_templates(id,slot,display_name,is_workout_day_only,is_rest_day_only,restricted_diet_only,goal_tags,is_active,sort_order) values('bk_mixed_eggs_dairy_free','breakfast','تخم‌مرغ و سفیده با نان سنگک',false,false,true,'{}',true,210) on conflict(id) do update set display_name=excluded.display_name,is_active=true;
delete from public.meal_template_slots where template_id='bk_mixed_eggs_dairy_free';
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('bk_mixed_eggs_dairy_free',0,'protein','egg_whole',true,null);
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('bk_mixed_eggs_dairy_free',1,'protein','egg_white',true,null);
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('bk_mixed_eggs_dairy_free',2,'starch','sangak_bread',true,null);
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('bk_mixed_eggs_dairy_free',3,'vegetable','fresh_cucumber_tomato',false,1);
insert into public.meal_templates(id,slot,display_name,is_workout_day_only,is_rest_day_only,restricted_diet_only,goal_tags,is_active,sort_order) values('as_restricted_fruit_avocado','afternoon_snack','کاسهٔ میوه و آووکادو',false,false,true,'{}',true,210) on conflict(id) do update set display_name=excluded.display_name,is_active=true;
delete from public.meal_template_slots where template_id='as_restricted_fruit_avocado';
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('as_restricted_fruit_avocado',0,'fruit','apple',true,null);
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('as_restricted_fruit_avocado',1,'fruit','banana',true,null);
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('as_restricted_fruit_avocado',2,'fat','avocado_half',true,null);
insert into public.meal_templates(id,slot,display_name,is_workout_day_only,is_rest_day_only,restricted_diet_only,goal_tags,is_active,sort_order) values('as_fruit_salad','afternoon_snack','سالاد میوهٔ سیب و موز',false,false,false,'{}',true,210) on conflict(id) do update set display_name=excluded.display_name,is_active=true;
delete from public.meal_template_slots where template_id='as_fruit_salad';
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('as_fruit_salad',0,'fruit','apple',true,null);
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('as_fruit_salad',1,'fruit','banana',true,null);
insert into public.meal_templates(id,slot,display_name,is_workout_day_only,is_rest_day_only,restricted_diet_only,goal_tags,is_active,sort_order) values('as_apple_oats','afternoon_snack','جو دوسر پخته با آب و سیب',false,false,false,'{}',true,210) on conflict(id) do update set display_name=excluded.display_name,is_active=true;
delete from public.meal_template_slots where template_id='as_apple_oats';
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('as_apple_oats',0,'starch','oats_dry',true,null);
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('as_apple_oats',1,'fruit','apple',true,null);
insert into public.meal_templates(id,slot,display_name,is_workout_day_only,is_rest_day_only,restricted_diet_only,goal_tags,is_active,sort_order) values('as_cheese_walnut_sangak','afternoon_snack','نان، پنیر و گردو با خیار و گوجه',false,false,false,'{}',true,210) on conflict(id) do update set display_name=excluded.display_name,is_active=true;
delete from public.meal_template_slots where template_id='as_cheese_walnut_sangak';
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('as_cheese_walnut_sangak',0,'starch','sangak_bread',true,null);
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('as_cheese_walnut_sangak',1,'dairy','low_fat_cheese',true,null);
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('as_cheese_walnut_sangak',2,'fat','walnut',true,null);
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('as_cheese_walnut_sangak',3,'vegetable','fresh_cucumber_tomato',true,null);
insert into public.meal_templates(id,slot,display_name,is_workout_day_only,is_rest_day_only,restricted_diet_only,goal_tags,is_active,sort_order) values('as_yogurt_banana_walnut','afternoon_snack','ماست، موز و گردو',false,false,false,'{}',true,210) on conflict(id) do update set display_name=excluded.display_name,is_active=true;
delete from public.meal_template_slots where template_id='as_yogurt_banana_walnut';
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('as_yogurt_banana_walnut',0,'dairy','low_fat_yogurt',true,null);
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('as_yogurt_banana_walnut',1,'fruit','banana',true,null);
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('as_yogurt_banana_walnut',2,'fat','walnut',true,null);
insert into public.meal_templates(id,slot,display_name,is_workout_day_only,is_rest_day_only,restricted_diet_only,goal_tags,is_active,sort_order) values('as_milk_small_dates','afternoon_snack','شیر کم‌چرب و خرمای کوچک',false,false,false,'{}',true,210) on conflict(id) do update set display_name=excluded.display_name,is_active=true;
delete from public.meal_template_slots where template_id='as_milk_small_dates';
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('as_milk_small_dates',0,'dairy','low_fat_milk',true,null);
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('as_milk_small_dates',1,'fruit','dates_small',true,null);
insert into public.meal_templates(id,slot,display_name,is_workout_day_only,is_rest_day_only,restricted_diet_only,goal_tags,is_active,sort_order) values('pw_whey_water','post_workout','یک اسکوپ وی با یک لیوان آب',true,false,false,'{}',true,210) on conflict(id) do update set display_name=excluded.display_name,is_active=true;
delete from public.meal_template_slots where template_id='pw_whey_water';
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('pw_whey_water',0,'protein','whey_protein',false,1);
insert into public.meal_templates(id,slot,display_name,is_workout_day_only,is_rest_day_only,restricted_diet_only,goal_tags,is_active,sort_order) values('pw_chicken_potato','post_workout','مرغ پخته و سیب‌زمینی آب‌پز',true,false,false,'{}',true,210) on conflict(id) do update set display_name=excluded.display_name,is_active=true;
delete from public.meal_template_slots where template_id='pw_chicken_potato';
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('pw_chicken_potato',0,'protein','chicken_breast',false,0.75);
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('pw_chicken_potato',1,'starch','boiled_potato',false,1);
insert into public.meal_templates(id,slot,display_name,is_workout_day_only,is_rest_day_only,restricted_diet_only,goal_tags,is_active,sort_order) values('pw_plant_bowl','post_workout','عدسی و سویا',true,false,false,'{}',true,210) on conflict(id) do update set display_name=excluded.display_name,is_active=true;
delete from public.meal_template_slots where template_id='pw_plant_bowl';
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('pw_plant_bowl',0,'protein','lentils_cooked',false,1.5);
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('pw_plant_bowl',1,'protein','soy_chunks',false,0.25);
insert into public.meal_templates(id,slot,display_name,is_workout_day_only,is_rest_day_only,restricted_diet_only,goal_tags,is_active,sort_order) values('pw_pea_water','post_workout','یک اسکوپ پروتئین نخود با آب',true,false,false,'{}',true,210) on conflict(id) do update set display_name=excluded.display_name,is_active=true;
delete from public.meal_template_slots where template_id='pw_pea_water';
insert into public.meal_template_slots(template_id,position,role,primary_food_item_id,dynamic_units,fixed_units) values('pw_pea_water',0,'protein','pea_protein',false,1);
commit;
