-- Behtan MVP — body-fat provenance + deterministic BMR policy
begin;

alter table public.user_profiles
  add column if not exists body_fat_source text;

alter table public.user_profiles
  drop constraint if exists user_profiles_body_fat_source_check;

alter table public.user_profiles
  add constraint user_profiles_body_fat_source_check
  check (body_fat_source is null or body_fat_source in ('ai_visual', 'measured'));

-- All body-fat values generated by the current Behtan onboarding flow came
-- from the visual AI scan. Mark legacy rows explicitly so formula selection
-- is deterministic and never inferred from presence of a number alone.
update public.user_profiles
set body_fat_source = 'ai_visual'
where body_fat_pct is not null
  and body_fat_source is null;

comment on column public.user_profiles.body_fat_source is
  'Provenance for body_fat_pct. ai_visual is informational and uses Mifflin-St Jeor; measured may use Katch-McArdle automatically.';

commit;
